name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install gtest manually
      run: sudo apt-get install -y libgtest-dev libeigen3-dev cmake && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && ls -a && cd lib && sudo cp *.a /usr/lib
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make
    - name: Run Tree Test
      run: cd build && ./runTreeTests
